### ISSUE TITLE
[FEAT]: please help me

### ISSUE THREAD

**Issue by kcraftcode** [JayantGoel001/LeetCode#1]
### Description

Your Github is very good.
I would like to learn the secret of how you joined so many organizations.

**Comment by JayantGoel001** [comment]
Hi @kentaurse,
Thanks for the compliment.
Well, there is no secret about how I joined so many organizations.
Most of these organizations provide a Bot-based joining.
For example:
https://github.com/Huniko-Team
https://github.com/Huniko-Team/community/issues/new?assignees=&labels=%E2%9C%89%EF%B8%8F+github-invitation&template=invitation.yml&title=Please+invite+me+to+the+Huniko+team

You can see they have provided a link to join their organization. Just create an issue and Bot will send you a request to join.

Happy Coding 😁

**Comment by kcraftcode** [comment]
thank you
